export interface ClientSettings {
  AMLProhibited:any;
  AMLVerified:any;
  JCJProhibited:any;
  CautionSuspension:any;
  SelfExcluded:any;
  SystemExcluded:any;
  TermsConditionsAcceptanceVersion:any;
  UnusedAmountWithdrawPercent:any;
  CasinoLayout:any;
  BlockedForInactivity:any;
  DocumentExpired:any;
  DocumentVerified:any;
  Excluded:any;
  IsAffiliateManager:any;
  MaxCredit:any;
  PasswordChangedDate:any;
  SessionLimit:any;
  Younger:any;
  AMLPercent:any;
}
